version: '3.8'

services:
  client:
    build: ./vite-client
    ports:
      - "5173:5173"

  express:
    build: ./express-server
    ports:
      - "3000:3000"
    depends_on:
      - spring

  spring:
    build: ./spring-server
    ports:
      - "8080:8080"
