version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "5173:5173"

  express:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - spring
      - python-backend

  spring:
    build: ./spring-backend
    ports:
      - "8091:8091"

  python-backend:
    build: ./python-backend
    ports:
      - "5001:5001"
