version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "5173:5173"

  express:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - spring

  spring:
    build: ./spring-backend
    ports:
      - "8091:8091"

  spring:
    build: ./python-backedn
    ports:
      - "3001:3001"
